
version: "3.4"

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.10
    environment:
      discovery.type: single-node
      xpack.security.enabled: 'false'
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  graylog:
    image: graylog/graylog:2.4
    ports:
      - 9000:9000
      # Plain TCP
      # - 5555:5555
      # GELF TCP
      # - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    environment:
      GRAYLOG_WEB_ENDPOINT_URI: "http://127.0.0.1:9000/api"
    volumes:
      - graylog:/usr/share/graylog/data/journal
    depends_on:
      - mongo
      - elasticsearch

  mongo:
    image: mongo:3
    volumes:
      - mongo:/data/db

volumes:
  mongo:
  elasticsearch:
  graylog:
